DBAIS/Pages/CheckPages/CheckAdd.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DBAIS.Models;
using DBAIS.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DBAIS.Pages.CheckPages
{
    [Authorize(Roles = "cashier, manager")]
    public class CheckAddModel : PageModel
    {
        // Form data
        [BindProperty] [MaxLength(13)] public string? CardNumber { get; set; }

        [BindProperty] [MaxLength(10)] public string CheckNumber { get; set; }

        public string IdEmployee { get; set; }

        [BindProperty] [DataType(DataType.Date)] public DateTime PrintDate { get; set; } = DateTime.Now;

        [BindProperty] [Range(0, 100)] public int Vat { get; set; } = 20;

        [BindProperty] public IList<Sale> Sales { get; set; } = ArraySegment<Sale>.Empty;

        public List<SelectListItem> EmployeeOptions { get; set; }
        public List<SelectListItem> CardsOptions { get; set; }

        private readonly EmployeeRepository _employeeRepository;
        private readonly CheckRepository _checkRepository;
        private readonly CustomerRepository _customerRepository;
        private readonly StoreProductRepository _storeProducts;

        private readonly UserManager<EmployeeUser> _userManager;

        public EmployeeUser? UserInfo { get; set; }

        public CheckAddModel(CheckRepository checkRepository, EmployeeRepository employeeRepository,
            CustomerRepository customerRepository, StoreProductRepository storeProducts,
            UserManager<EmployeeUser> userManager)
        {
            _checkRepository = checkRepository;
            _employeeRepository = employeeRepository;
            _customerRepository = customerRepository;
            _storeProducts = storeProducts;
            _userManager = userManager;
        }

        private async Task InitModel()
        {
            var employees = await _employeeRepository.GetCashiers(Sort.None);
            EmployeeOptions = employees.Select(e =>
                new SelectListItem
                {
                    Value = e.Id,
                    Text = e.Id
                }).ToList();
            var cards = await _customerRepository.GetCards(null);
            CardsOptions = new List<SelectListItem>();
            CardsOptions.Add(new SelectListItem
            {
                Value = "",
                Text = "-"
            });
            CardsOptions.AddRange(cards.Select(c =>
                new SelectListItem
                {
                    Value = c.Number,
                    Text = c.Number
                }).ToList());
            if (User.IsInRole("cashier") || User.IsInRole("manager"))
            {
                UserInfo = await _userManager.FindByNameAsync(User.Identity.Name);
                IdEmployee = UserInfo.Id;
            }
        }

        public async Task<IActionResult> OnGetAsync()
        {
            await InitModel();
            return Page();
        }

        public async Task<IActionResult> OnGetPrice([FromQuery] string upc)
        {
            try
            {
                var product = await _storeProducts.GetProduct(upc);
                return new JsonResult(new {price = product.Price, count = product.Count});
            }
            catch (EntityNotFoundException<StoreProduct, string>)
            {
                return new JsonResult(null);
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await InitModel();
            if (!ModelState.IsValid)
            {
                return Page();
            }
            else
            {
                var sum = Sales.Sum(s => s.Price * s.Count);
                var vat = sum * Vat / 100m;
                var newCheck = new Models.Check
                {
                    Number = CheckNumber,
                    CardNum = CardNumber != "" ? CardNumber : null,
                    Date = PrintDate,
                    EmployeeId = IdEmployee,
                    Total = sum + vat,
                    Vat = vat,
                    Sales = Sales
                };
                await _checkRepository.AddCheck(newCheck);
                return Redirect("/checks");
            }
        }
    }
}

DBAIS/Pages/CheckPages/CheckUpdate.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DBAIS.Models;
using DBAIS.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DBAIS.Pages.CheckPages
{
    [Authorize(Roles = "cashier, manager")]
    public class CheckUpdateModel : PageModel
    {

        // Current check
        public Check CurrentCheck { get; set; }

        // Form data
        [BindProperty]
        [MaxLength(13)]
        public string? CardNumber { get; set; }


        [BindProperty]
        [DataType(DataType.Date)]
        public DateTime PrintDate { get; set; }


        public List<SelectListItem> EmployeeOptions { get; set; }
        public List<SelectListItem> CardsOptions { get; set; }


        private readonly EmployeeRepository _employeeRepository;
        private readonly CheckRepository _checkRepository;
        private readonly CustomerRepository _customerRepository;
        private readonly StoreProductRepository _storeProductRepository;
        private readonly UserManager<EmployeeUser> _userManager;


        public EmployeeUser UserInfo { get; set; }

        public CheckUpdateModel(CheckRepository checkRepository, EmployeeRepository employeeRepository, CustomerRepository customerRepository, UserManager<EmployeeUser> userManager, StoreProductRepository storeProductRepository)
        {
            _checkRepository = checkRepository;
            _employeeRepository = employeeRepository;
            _customerRepository = customerRepository;
            _userManager = userManager;
            _storeProductRepository = storeProductRepository;
        }

        private async Task InitModel(string id)
        {
            UserInfo = await _userManager.FindByNameAsync(User.Identity.Name);

            var checks = await _checkRepository.GetChecks(null, null, null);
            CurrentCheck = checks.Find(x => x.Number.Equals(id));

            var employees = await _employeeRepository.GetCashiers(Sort.None);
            EmployeeOptions = employees.Select(e =>
                                  new SelectListItem
                                  {
                                      Value = e.Id,
                                      Text = e.Id
                                  }).ToList();
            var cards = await _customerRepository.GetCards(null);
            CardsOptions = new List<SelectListItem>();
            CardsOptions.AddRange(cards.Select(c =>
                                  new SelectListItem
                                  {
                                      Value = c.Number,
                                      Text = c.Number,
                                      Selected = c.Number.Equals(CurrentCheck.CardNum)
                                  }).ToList());
            PrintDate = CurrentCheck.Date;
        }
        public async Task<IActionResult> OnGetAsync(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await InitModel(id);
            if (CurrentCheck == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostCreateSale([FromForm] string id, [FromForm] string upc, [FromForm] int count)
        {
            if (id == null)
            {
                return NotFound();
            }
            await InitModel(id);
            if (CurrentCheck == null)
            {
                return NotFound();
            }
            try
            {
                var prod = await _storeProductRepository.GetProduct(upc);
                if (prod.Count < count)
                {
                    ModelState.AddModelError("", "There are only " + prod.Count + " units of " + prod.Upc + " product in the storage");
                    return Page();
                }
                var newSale = new Sale
                {
                    Check = id,
                    Upc = upc,
                    Count = count,
                    Price = prod.Price
                };
                CurrentCheck.Sales.Add(newSale);
                var newTotal = CurrentCheck.Sales.Sum(x => x.Price * x.Count);
                CurrentCheck.Total = newTotal;
            
                await _checkRepository.UpdateCheck(CurrentCheck);
            }
            catch
            {
                ModelState.AddModelError("","Wrong upc entered");
            }
            await InitModel(id);
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteSale([FromForm] string id, [FromForm] string upc)
        {
            await _checkRepository.DeleteProductFromCheck(id, upc);
            if (id == null)
            {
                return NotFound();
            }
            await InitModel(id);
            if (CurrentCheck == null)
            {
                return NotFound();
            }
            var newTotal = CurrentCheck.Sales.Sum(x => x.Price*x.Count);
            CurrentCheck.Total = newTotal;
            await _checkRepository.UpdateCheck(CurrentCheck);
            await InitModel(id);
            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromRoute] string id)
        {
            await InitModel(id);
            if (!ModelState.IsValid)
            {
                return Page();
            }
            else
            {
                var newTotal = CurrentCheck.Sales.Sum(x => x.Price * x.Count);
                var newCheck = new Check
                {
                    CardNum = CardNumber != "" ? CardNumber : null,
                    Date = PrintDate,
                    Sales = CurrentCheck.Sales,
                    EmployeeId = CurrentCheck.EmployeeId,
                    Number = id,
                    Total = newTotal,
                    Vat = CurrentCheck.Vat
                };
                await _checkRepository.UpdateCheck(newCheck);
                return Redirect("/checks");
            }
        }
    }
}

DBAIS/Pages/CheckPages/ChecksPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DBAIS.Models;
using DBAIS.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DBAIS.Pages.CheckPages
{
    [Authorize(Roles = "cashier, manager")]
    public class ChecksPageModel : PageModel
    {

        [BindProperty]
        [DataType(DataType.Date)]
        public DateTime DateFrom { get; set; }

        [BindProperty]
        [DataType(DataType.Date)]
        public DateTime DateTo { get; set; } = DateTime.Now;

        private readonly CheckRepository _checkRepository;
        private readonly EmployeeRepository _employeeRepository;
        private readonly UserManager<EmployeeUser> _userManager;

        public EmployeeUser? UserInfo {get; set;}

        [BindProperty]
        public string? SelectedEmployee { get; set; }

        public ChecksPageModel(CheckRepository checkRepository, EmployeeRepository employeeRepository, UserManager<EmployeeUser> userManager)
        {
            _checkRepository = checkRepository;
            _employeeRepository = employeeRepository;
            _userManager = userManager;
        }

        public List<Check> Checks { get; set; }

        public async Task OnGetAsync()
        {
            if (User.IsInRole("cashier"))
            {
                UserInfo = await _userManager.FindByNameAsync(User.Identity.Name);
                Checks = await _checkRepository.GetChecks(UserInfo.Id, null, null);
            }
            else if (User.IsInRole("manager"))
            {
                Checks = await _checkRepository.GetChecks(null, null, null);
            }
        }

        public async Task OnGetByPeriod([FromQuery] DateTime dateFrom, [FromQuery] DateTime dateTo)
        {
            if (User.IsInRole("cashier"))
            {
                DateFrom = dateFrom;
                DateTo = dateTo;
                UserInfo = await _userManager.FindByNameAsync(User.Identity.Name);
                Checks = await _checkRepository.GetChecks(UserInfo.Id, dateFrom, dateTo);
            }
            else if (User.IsInRole("manager"))
            {
                Checks = await _checkRepository.GetChecks(null, null, null);
            }
        }

        public async Task OnGetByEmployee([FromQuery] string? employeeId)
        {
            SelectedEmployee = employeeId;
            Checks = await _checkRepository.GetChecks(employeeId, null, null);
        }

        public async Task<IActionResult> OnPostDeleteAsync(string id)
        {
            try
            {
                await _checkRepository.DeleteCheck(id);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "You can`t delete this check");
            }
            Checks = await _checkRepository.GetChecks(null, null, null);
            return Page();
        }
    }
    public enum StoreProductSort
    {
        None,
        NameAscending,
        NameDescending,
        CountAscending,
        CountDescending
    }
}

DBAIS/Pages/CheckPages/CheckAdd.cshtml
@page "/checks/add"
@model DBAIS.Pages.CheckPages.CheckAddModel
@{
    Layout = "_Shared/_MasterLayoutPage";
}
<div>
    <!-- Toggle menu -->
    @{
        Dictionary<string, string> breadcrumbRoutes = new Dictionary<string, string>
        {
            {"/", "Home"},
            {"/checks", "Checks"},
            {"/checks/add", "Add"},
        };

    }
    <partial name="_ToggleSidebarWithBreadcrumbs" model="@breadcrumbRoutes"/>
    <!-- Content -->
    <div>
        @{
            var header = "Create new check";
        }
        <partial name="_EditPageHeader" model="@header"/>
        @if (ModelState.ErrorCount > 0)
        {
            <div id="book-alert" class="alert alert-danger" role="alert" style="{margin:10px;}">
                <div class="validation" asp-validation-summary="All"></div>
            </div>
        }
        <form method="post" enctype="multipart/form-data">
            <div id="check-form" class="form-group">
                <div class="row">
                    <div class="col-3">
                        <label asp-for="CheckNumber">Check number</label>
                        <input asp-for="CheckNumber" class="form-control" placeholder="Check number">
                    </div>
                    <div class="col-3">
                        <label>Employee ID</label>
                        <p>@Model.UserInfo.Id</p>
                    </div>
                </div>
                <br/>
                <div class="row">
                    <div class="col-3">
                        <label asp-for="PrintDate">Print date</label>
                        <input type="date" asp-for="PrintDate" class="form-control" placeholder="Date printed"/>
                    </div>
                    <div class="col-3">
                        <label asp-for="Vat">Vat %</label>
                        <input asp-for="Vat" class="form-control" placeholder="VAT">
                    </div>
                </div>
                <br/>
                <div class="row">
                    <div class="col-3">
                        <label asp-for="CardNumber">Card number</label>
                        <input asp-for="CardNumber" class="form-control" />
                    </div>
                </div>
                <br/>
                <div id="items">
                    <div class="col-2">
                        <button class="btn btn-secondary" onclick="return addProduct()">Add Product</button>
                    </div>
                    <br/>
                    @for (var i = 0; i < Model.Sales.Count; i++)
                    {
                        var sale = Model.Sales[i];
                        <div class="row" data-row="@i">
                            <div class="col-3">
                                <label>
                                    UPC:
                                    <input type="text" name="Sales[@i].Upc" class="form-control upc" required value="@sale.Upc"/>
                                </label>
                            </div>
                            <div class="col-2">
                                <label>
                                    Amount:
                                    <input type="number" min="0" name="Sales[@i].Count" value="@sale.Count" class="form-control count" required />
                                </label>
                            </div>
                            <div class="col-2">
                                <label>
                                    Price:
                                    <input type="number" name="Sales[@i].Price" value="@sale.Price" class="form-control price" readonly required/>
                                </label>
                            </div>
                            <div class="col-2">
                                <label>
                                    Subtotal:
                                    <input type="number" value="@(sale.Price * sale.Count)" class="form-control subtotal" disabled/>
                                </label>
                            </div>
                            <div class="col-2 remove-wrapper">
                                <button class="btn btn-secondary remove-item">Remove</button>
                            </div>
                        </div>
                    }
                </div>
                <br/>
                <div class="row">
                    Total: <span id="total">0</span>
                </div>
                <br/>
                <div class="row">
                    <div class="col-2">
                        <a href="/checks">
                            <button type="button" class="btn btn-secondary">Cancel</button>
                        </a>
                    </div>
                    <div class="col-2">
                        <input type="submit" class="btn btn-success" value="Create Check">
                    </div>
                </div>
            </div>
        </form>


    </div>
</div>

@section Styles {
    <style>
        .remove-wrapper {
            position: relative;
        }
    
        .remove-item {
            position: absolute;
            bottom: 9px;
        }
    </style>
}

@section Scripts {
    <script>
        let counter = @Model.Sales.Count;
        function addProduct() {
            $('#items').append(`
                <div class="row" data-row="${counter}">
                    <div class="col-3">
                        <label>UPC: 
                        <input  type="text" name="Sales[${counter}].Upc" class="form-control upc" required/>
                        </label>
                    </div>
                    <div class="col-2">
                        <label>Amount: 
                        <input type="number" min="0" name="Sales[${counter}].Count" value="1" class="form-control count" required/>
                        </label>
                    </div>
                    <div class="col-2">
                        <label>Price: 
                            <input type="number" name="Sales[${counter}].Price" value="0" class="form-control price" readonly required/>
                        </label>
                    </div>
                    <div class="col-2">
                        <label>Subtotal: 
                            <input type="number" value="0" class="form-control subtotal" disabled/>
                        </label>
                    </div>
                    <div class="col-2 remove-wrapper">
                        <button class="btn btn-secondary remove-item">Remove</button>
                    </div>
                </div>
            `);
            counter++;
            return false;
        }
        
        $(document).on('change', '.upc', function() {
          loadPrices($(this));
        });
        
        function loadPrices($upc) {
          const $row = $upc.closest('.row');
          const upc = $upc.val();
          fetch(`?handler=price&upc=${upc}`)
          .then(r => r.json())
          .then(r => {
                  if (r){
                    $row.find('.price').val(r.price);
                    $row.find('.count').attr('max', r.count);
                    updateSubTotal($row);
                    $upc.get(0).setCustomValidity('');
                  } else {
                      $upc.get(0).setCustomValidity('Unknown UPC');
                  }
              });
        }
        
        $(document).on('change', '.count', function() {
            updateSubTotal($(this).closest('.row'));
        });
        
        $(document).on('click', '.remove-item', function() {
            const row = $(this).closest('.row');
            let index = row.data('row');
            row.nextAll().each(function() {
              const r = $(this);
              r.find('.upc').attr('name', `Sales[${index}].Upc`);
              r.find('.price').attr('name', `Sales[${index}].Price`);
              r.find('.count').attr('name', `Sales[${index}].Count`);
              r.data('row', index);
              index++;
            });
            row.remove();
            counter = index;
            updateTotal();
        });
        
        function updateSubTotal($row){
            const count = parseInt($row.find('.count').val());
            const price = parseFloat($row.find('.price').val());
            const total = count * price;
            $row.find('.subtotal').val(total);
            updateTotal();
        }
        
        function updateTotal()
        {
            let total = 0;
            $('#check-form').find('.subtotal').each(function() {
              total += parseFloat($(this).val());
            });
            $('#total').text(total);
        }
        
        $('.upc').each(function() {
          loadPrices($(this));
        })
        
    </script>
}

DBAIS/Pages/CheckPages/CheckUpdate.cshtml
@page "/checks/update/{id}"
@model DBAIS.Pages.CheckPages.CheckUpdateModel
@{
    Layout = "_Shared/_MasterLayoutPage";
}
<div>
    <!-- Toggle menu -->
    @{
        Dictionary<string, string> breadcrumbRoutes = new Dictionary<string, string>
{
                    {"/", "Home"},
                    {"/checks", "Checks"},
                    {"/checks/update", "Update"},
                };

    }
    <partial name="_ToggleSidebarWithBreadcrumbs" model="@breadcrumbRoutes" />
    <!-- Content -->
    <div>
        @{
            var header = "Current check number: " + Model.CurrentCheck.Number;
        }
        <partial name="_EditPageHeader" model="@header" />
        @if (ModelState.ErrorCount > 0)
        {
            <div id="book-alert" class="alert alert-danger" role="alert" style="{margin:10px;}">
                <div class="validation" asp-validation-summary="All"></div>
            </div>
        }
        <form method="post">
            <div class="form-group">
                <div class="row">
                    <div class="col-3">
                        <label asp-for="PrintDate">Print date</label>
                        <input asp-for="PrintDate" class="form-control" placeholder="Date printed" value="@Model.PrintDate.Date.ToString("yyyy-MM-dd")">
                    </div>
                    <div class="col-3">
                        <label asp-for="CardNumber">Card number</label>
                        <select asp-for="CardNumber" asp-items="@Model.CardsOptions" class="form-control" placeholder="Card number"></select>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-2">
                        <a href="/checks">
                            <button type="button" class="btn btn-secondary">Cancel</button>
                        </a>
                    </div>
                    @if (User.IsInRole("manager"))
                    {
                        <div class="col-2">
                            <input type="submit" class="btn btn-success" value="Update Check Info">
                        </div>
                    }
                </div>
            </div>
        </form>

        @if (User.IsInRole("manager"))
        {
            var header2 = "Add products to check";
            <partial name="_EditPageHeader" model="@header2" />
            <form method="post" asp-page-handler="CreateSale">
                <div class="form-group">
                    <div class="row">
                        <input name="id" hidden value="@Model.CurrentCheck.Number" />
                        <div class="col-2">
                            <input type="text" name="upc" class="form-control" placeholder="UPC" required>
                        </div>
                        <div class="col-2">
                            <input type="number" min="1" name="count" class="form-control" placeholder="Count" required>
                        </div>
                        <div class="col-2">
                            <input type="submit" class="btn btn-success" value="Create Sale">
                        </div>
                    </div>
                </div>
            </form>
        }
        @if (User.IsInRole("cashier"))
        {
            var header2 = "Check products";
            <partial name="_EditPageHeader" model="@header2" />
        }
        <hr />
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Upc</th>
                    <th scope="col">Count</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var sale in Model.CurrentCheck.Sales)
                {
                    <tr>
                        <td>@sale.Upc</td>
                        <td>@sale.Count</td>
                        <td>@sale.Price</td>
                        <td>
                            @if (User.IsInRole("manager"))
                            {
                                <form method="post" asp-page-handler="DeleteSale">
                                    <input name="id" hidden value="@Model.CurrentCheck.Number" />
                                    <input name="upc" hidden value="@sale.Upc" />
                                    <input type="submit" class="btn btn-danger" value="Delete">
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

DBAIS/Pages/CheckPages/ChecksPage.cshtml
@page "/checks"
@model DBAIS.Pages.CheckPages.ChecksPageModel
@{
    ViewBag.Title = "Checks";
    Layout = "_Shared/_MasterLayoutPage";
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <partial name="_ToggleSidebarButton" />
        @if (User.IsInRole("manager") || User.IsInRole("cashier"))
        {
            <div class="col-1">
                <a href="/checks/add">
                    <button type="button" class="btn btn-success">Add +</button>
                </a>
            </div>
        }
        <div class="col">

        </div>
        <div>
            <form method="get">
                <div class="input-group">
                    <input type="hidden" name="handler" value="ByPeriod" />
                    <label class="form-check-label" asp-for="DateFrom" style="margin-top:6px;margin-right:6px;">
                        From
                    </label>
                    <input class="form-control" type="date" asp-for="DateFrom" value="@(@Model.DateFrom != null ? @Model.DateFrom.Date.ToString("yyyy-MM-dd"):"")">
                    <div class="col-1">

                    </div>
                    <label class="form-check-label" asp-for="DateTo" style="margin-top:6px;margin-right:6px;">
                        To
                    </label>
                    <input class="form-control" type="date" asp-for="DateTo" value="@(@Model.DateFrom != null ? @Model.DateTo.Date.ToString("yyyy-MM-dd"):"")">
                    <div class="input-group-append">
                        <input class="btn btn-outline-secondary" type="submit" value="Get">
                    </div>
                </div>
            </form>
        </div>
        @if (User.IsInRole("manager"))
        {
            <div class="col">

            </div>
            <div>
                <form method="get">
                    <div class="input-group">
                        <input type="hidden" name="handler" value="ByEmployee" />
                        <input class="form-control" asp-for="SelectedEmployee" name="employeeId" placeholder="Employee ID" />
                        <div class="input-group-append">
                            <input class="btn btn-outline-secondary" type="submit" value="Get">
                        </div>
                    </div>
                </form>
            </div>
        }

    </div>
</nav>

<h1>Checks</h1>
@if (ModelState.ErrorCount > 0)
{
    <div id="book-alert" class="alert alert-danger" role="alert" style="{margin:10px;}">
        <div class="validation" asp-validation-summary="All"></div>
    </div>
}
<table class="table">
    <thead>
        <tr>
            <th scope="col">Check Number</th>
            <th scope="col">Client card</th>
            <th scope="col">Employee Id</th>
            <th scope="col">Date</th>
            <th scope="col">Total</th>
            <th scope="col">Vat</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var check in Model.Checks)
        {
        <tr>
            <td>@check.Number</td>
            <td>@(check.CardNum != null ? check.CardNum : "-")</td>
            <td>@check.EmployeeId</td>
            <td>@check.Date</td>
            <td>@check.Total</td>
            <td>@check.Vat</td>
            <td>
                @if (User.IsInRole("manager"))
                {
                    <a asp-page="CheckUpdate" asp-route-id="@check.Number" class=" text-primary link-primary">Update</a>
                }
                @if (User.IsInRole("cashier"))
                {
                    <a asp-page="CheckUpdate" asp-route-id="@check.Number" class=" text-primary link-primary">Info</a>
                }
            </td>
            <td>
                @if (User.IsInRole("manager"))
                {
                    <form method="post">
                        <input type="submit" asp-page-handler="delete" asp-route-id="@check.Number" class="btn btn-danger" value="Delete">
                    </form>
                }
            </td>
        </tr>
        }
    </tbody>
</table>